homepage/urls.py
from django.urls import path
from . import views

app_name = 'homepage'

urlpatterns = [
	path('', views.index, name = "index"),
	path('about/', views.about, name = "about"),
	path('skill/', views.skill, name = "skill"),
	path('experience/', views.experience, name = "experience"),
	path('galeri/', views.galeri, name = "galeri"),
	path('contact/', views.contact, name = "contact"),
	path('schedule_add', views.schedule_add, name="schedule_add"),
	path('schedule_detail', views.schedule_detail, name="schedule_detail"),
	path('schedule_edit/<int:pk>', views.schedule_edit, name='schedule_edit'),
	path('schedule_delete/<int:pk>', views.schedule_delete, name='schedule_delete'),
	path('del_schedule', views.del_schedule, name='del_schedule'),
]

story4/urls.py
from django.conf.urls import include
from django.conf.urls import include
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.core.exceptions import ImproperlyConfigured
from django.conf.urls.static import static
from django.conf import settings
import os

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

homepage/models.py
from django.db import models
import datetime

Category=[('Tugas','Tugas'),('Kuis','Kuis'),('UTS','UTS'),('UAS','UAS'),('Rapat','Rapat'),
			('Wawancara','Wawancara')]

class Schedule(models.Model):
	activity = models.CharField(max_length=100)
	dates = models.DateField()
	time = models.TimeField()
	location = models.CharField(max_length=100)
	category = models.CharField(max_length=100, choices=Category)

homepage/forms.py
from django import forms
from .models import Schedule
from django.forms import ModelForm

class ScheduleForm(ModelForm):
	class Meta:
		model= Schedule
		fields = ['activity','dates', 'time', 'location', 'category']
		labels = {
			'activity' : 'Activity','dates' : 'Date', 'time' : 'Time', 'location' : 'Location', 'category' : 'Category'
		}
		widgets = {
			'activity' : forms.TextInput(attrs={'class': 'form-control',
										'type' : 'text',
										'placeholder' : 'Apa yang ingin kamu lakukan?'}),
			'dates' : forms.DateInput(attrs={'class': 'form-control',
										'type' : 'date'}),
			'time' : forms.TimeInput(attrs={'class': 'form-control',
										'type' : 'time'}),
			
			'location' : forms.TextInput(attrs={'class' : 'form-control',
										'type' : 'text',
										'placeholder' : 'Dimanakah tempatnya?'}),
			'category' : forms.Select(attrs={'class': 'form-control'})
		}

homepage/views.py
from django.shortcuts import render
from .forms import ScheduleForm
from .models import Schedule
from django.shortcuts import redirect
import datetime

# Create your views here.
def index(request):
	return render(request, 'index.html')

def about(request):
	return render(request, 'about.html')

def skill(request):
	return render(request, 'skill.html')

def experience(request):
	return render(request, 'experience.html')

def galeri(request):
	return render(request, 'galeri.html')

def contact(request):
	return render(request, 'contact.html')

def schedule_add(request):
    if request.method == 'POST':
        form = ScheduleForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('homepage:schedule_detail')
    else:
        form = ScheduleForm()

    content = {'title' : 'Form Schedule',
                'form' : form}

    return render(request, 'schedule_form.html', content)

def schedule_detail(request):
    data = Schedule.objects.all()
    content = {'title' : 'Schedule',
                'data' : data}
    return render(request, 'schedule.html', content)

def schedule_edit(request, pk):
    post = Schedule.objects.get(pk=pk)
    if request.method == "POST":
        form = ScheduleForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('homepage:schedule_detail')
    else:
        form = ScheduleForm(instance=post)

    content = {'title' : 'Form Schedule',
                'form' : form,
                'obj' : post}
    return render(request, 'schedule_edit.html', content)

def schedule_delete(request, pk):
    Schedule.objects.filter(pk=pk).delete()
    data = Schedule.objects.all()
    content = {'title' : 'Schedule',
                'data' : data}
    return redirect('homepage:schedule_detail')

def del_schedule(request):
    if request.method == "POST":
        Schedule.objects.all().delete()
        data = Schedule.objects.all()
        content = {'title' : 'Schedule',
                'data' : data}
        return redirect('homepage:schedule_detail')
    return redirect('homepage:schedule_detail')

homepage/templates/about.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} About {% endblock %}

{% block content %}
	<section id="about">
		<h1>About</h1>
		<hr>
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-md-6">
					<img src="{% static 'img/profil.png' %}">
				</div>
				<div class="col-md-3" id="first">
					<p>Full Name</p>
				    <p>Nickname</p>
				    <p>Birthday</p>
				    <p>Address</p>
				    <p>Phone</p>
				    <p>Web</p>
				    <p>Hobby</p>
				</div>
				<div class="col-sm-6 col-md-3">
					<p>Anatasya Dwijayanti Chang</p>
				    <p>Ana</p>
				    <p>30 Oktober 2000</p>
				    <p>Perumnas, Bekasi</p>
				    <p>+62 85770356131</p>
				    <p>anatasyadwijayanti.herokuapp.com</p>
				    <p>Listening to music and watching korean drama</p>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

homepage/templates/base.html
<!DOCTYPE html>
<html lang="en">
{% load static %}
<head>
	<meta charset="utf-8">
	<title>{% block title %} {% endblock %}</title>
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<link rel="stylesheet" href="{%static 'css/style.css' %}">
	<link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">

</head>
<body id="page-top">
	<header>
		<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
			<div class="container">
	  		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
	    		<span class="navbar-toggler-icon"></span>
	  		</button>
	  
	  		<div class="collapse navbar-collapse justify-content-center " id="navbarNav">
	    		<ul class="navbar-nav">
	    			<li class="nav-item">
	        			<a class="nav-link" href="{% url 'homepage:index' %}">Home</a>
	      			</li>
	      			<li class="nav-item">
	        			<a class="nav-link" href="{% url 'homepage:about' %}">About</a>
	      			</li>
	      			<li class="nav-item">
	        			<a class="nav-link" href="{% url 'homepage:skill' %}">Skill</a>
	      			</li>
	      			<li class="nav-item">
	        			<a class="nav-link" href="{% url 'homepage:experience' %}">Experience</a>
	      			</li>
	      			<li class="nav-item">
	        			<a class="nav-link" href="{% url 'homepage:galeri' %}">Gallery</a>
	      			</li>
	      			<li class="nav-item">
	        			<a class="nav-link" href="{% url 'homepage:contact' %}">Contact</a>
	      			</li>
	      			<li class="nav-item">
	        			<a class="nav-link" href="{% url 'homepage:schedule_add' %}">Schedule</a>
	      			</li>

	    		</ul>
	  		</div>
	  		</div>
		</nav>
	</header>
	
	{% block content %}
	{% endblock content%}
	

	<!-- <script type="text/javascript" src="js/bootstrap.min.js"></script> -->
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
	
</body>
</html>

homepage/templates/contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Contact {% endblock %}

{% block content %}
	<section id="contact">
		<h1>Contact</h1>
		<hr>
		<form>
		  <div class="row">
		    <div class="col">
		      <input type="text" class="form-control" placeholder="Your Name">
		    </div>
		    <div class="col">
		      <input type="email" class="form-control" placeholder="Your Email">
		    </div>
		  </div>
		</form>
		<div class="form-group">
		   	<textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Message"></textarea>
		</div>
		<div class="btn-group" role="group" aria-label="Basic example">
	  		<button type="button" class="btn btn-secondary">Send</button>
	  	</div>
	  	<br>

		<a href="https://www.linkedin.com/in/anatasyadc/">
			<img src="{%static 'img/linkedin.png' %}">
		</a>
		<a href="https://www.instagram.com/anatasyadc/">
			<img src="{%static 'img/instagram.png' %}">
		</a>
		<a href="https://twitter.com/anatasyadwijaya">
			<img src="{%static 'img/twitter.png' %}">
		</a>	
	</section>
{% endblock %}

homepage/templates/experience.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Experience {% endblock %}

{% block content %}
	<section id="experience">
		<h1>Experience</h1>
		<hr>
		<div class="container">
			<div class="row">
				<div class="col">
					<h2>Committes Experience</h2>
					<br>
					<h3>SIWAK-NG</h3>
					<div class="row">
						<div class="col">
							<p>Vice Person in Charge Accomodations</p>
						</div>
						<div class="col">
							<p>Feb 2019 - Present</p>
						</div>
					</div>
					<h3>Wisuda Genap</h3>
					<div class="row">
						<div class="col">
							<p>Vice Person in Charge Food and Beverages</p>
						</div>
						<div class="col">
							<p>Feb 2019 - Agu 2019</p>
						</div>
					</div>
					<h3>COMPFEST</h3>
					<div class="row">
						<div class="col">
							<p>Staff of Data Science Academy</p>
						</div>
						<div class="col">
							<p>Feb 2019 - July 2019</p>
						</div>
					</div>
					<h3>Wisuda Ganjil</h3>
					<div class="row">
						<div class="col">
							<p>Staff of Food and Beverages</p>
						</div>
						<div class="col">
							<p>Dec 2019 - Jan 2019</p>
						</div>
					</div>
					
				</div>
				<div class="col">
					<h2>Organization Experience</h2>
					<br>
					<h3>FUKI Fasilkom UI</h3>
					<div class="row">
						<div class="col">
							<p>Staff of Muslimah Center</p>
						</div>
						<div class="col">
							<p>Feb 2019 - Present</p>
						</div>
					</div>
					<br>
					<br>
					<br>
					<h2>Volunteer Experience</h2>
					<br>
					<h3>Dasar Dasar Pemograman 0</h3>
					<div class="row">
						<div class="col">
							<p>Mentor</p>
						</div>
						<div class="col">
							<p>Agu 2019 </p>
						</div>
					</div>
					<h3>Pocman</h3>
					<div class="row">
						<div class="col">
							<p>Volunteer</p>
						</div>
						<div class="col">
							<p>Sep 2018 - Nov 2018</p>
						</div>
					</div>
				</div>
			</div>
		</div>
	</section>
{% endblock %}

homepage/templates/galeri.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Galeri {% endblock %}

{% block content %}
	<section id="galeri">
    <h1>Galeri</h1>
    <hr>
    <div class="container">
      <div class="row">
        <div class="col-md-4">
          <img src="{%static 'img/1533807681803.jpg' %}">
          <div class="overlay">Kelompok 44 OKK UI</div>
        </div>
        <div class="col-md-4">
          <img src="{%static 'img/1548922477535.jpg' %}">
          <div class="overlay">Divisi Konsumsi Wisuda Ganjil 2019</div>
        </div>
        <div class="col-md-4">
          <img src="{%static 'img/1550500602829.jpg' %}">
          <div class="overlay">Muslimah Center FUKI</div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <img src="{%static 'img/1536497141567.jpg' %}">
          <div class="overlay">Pocman</div>
        </div>
        <div class="col-md-4">
          <img src="{%static 'img/1543141949071.jpg' %}">
          <div class="overlay">Kelompok Kecil Beyla</div>
        </div>
        <div class="col-md-4">
          <img src="{% static 'img/1543136887405.jpg' %}">
          <div class="overlay">Kelompok Besar Lyra</div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-4">
          <img src="{% static 'img/line_821235995953109.jpg' %}">
          <div class="overlay">Data Science Academy Compfest</div>
        </div>
        <div class="col-md-4">
          <img src="{% static 'img/1560082973984.jpg' %}">
          <div class="overlay">Divisi Akomodasi SIWAK-NG</div>
        </div>
        <div class="col-md-4">
          <img src="{% static 'img/line_42438680065914.jpg' %}">
          <div class="overlay">Divisi Konsumsi Wisuda Genap 2019</div>
        </div>
      </div>
    </div>
	</section>
{% endblock %}

homepage/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Home {% endblock %}

{% block content %}
	<section id="home">
		<div class="row">
		  <div class="col-md-4">
		  	<img src=" {% static 'img/foto header.jpg' %}" class="img-responsive">
		  </div>
		  <div class="col-md-8 align-self-center text-center">
		  	<h1 class="font-weight-bold">Anatasya<br>Dwijayanti</h1>
		  	<h4>Information System Student</h4>
		  	<h4>Universitas Indonesia</h4>	
		  	<br><br>
		  </div>
		</div>
	</section>
{% endblock %}

homepage/templates/schedule.html
{% extends 'base.html' %}
{% block title %} {{title}}{% endblock %}
{% load staticfiles %}

{% block content %}
<div id="sched">
    <div class="container">
        <h1>Schedule</h1>
        <hr>
        <div class="col-md-12 left">
            <form method="POST" action="{% url 'homepage:del_schedule' %}">
                {% csrf_token %}
                <button>Delete All</button>
            </form>

            <a href="{% url 'homepage:schedule_add' %}">
            <button type="button">Add Schedule</button></a>
            <table class="table m-0">
                <thead>
                    <tr>
                        <th>Activity</th>
                        <th>Day</th>
                        <th>Date</th>
                        <th>Time</th>
                        <th>Location</th>
                        <th>Category</th>
                        <th>Edit</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obj in data %}
                    <tr>
                        <td>{{ obj.activity }}</td>
                        <td>{{ obj.dates|date:"l" }}</td>
                        <td>{{ obj.dates }}</td>
                        <td>{{ obj.time }}</td>
                        <td>{{ obj.location }}</td>
                        <td>{{ obj.category }}</td>
                        <td><a href="{% url 'homepage:schedule_edit' pk=obj.pk %}">
                        	<button type="button">Edit</button></a></td>
                        <td><a href="{% url 'homepage:schedule_delete' pk=obj.pk %}">
                        	<button type="button">Delete</button></a></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>

{% endblock %}

homepage/templates/schedule_edit.html
{% extends 'base.html' %}
{% block title %} {{title}}{% endblock %}
{% load staticfiles %}

{% block content %}
<div id="sched">
    <div class="container">
        <h1>Schedule</h1>
        <hr>
        <form class="left" style="width: 50%; margin: 0 auto" method="POST" action="{% url 'homepage:schedule_edit' pk=obj.pk %}" novalidate>
            {% csrf_token %}
            <div class="form-group">
                <label for="activity"><strong>{{ form.activity.label_tag }}</strong></label>
                {{ form.activity }}
            </div>
            <div class="form-group">
                <label for="dates"><strong>{{ form.dates.label_tag }}</strong></label>
                {{ form.dates }}
            </div>
            <div class="form-group">
                <label for="time"><strong>{{ form.time.label_tag }}</strong></label>
                {{ form.time }}
            </div>
            <div class="form-group">
                <label for="location"><strong>{{ form.location.label_tag }}</strong></label>
                {{ form.location }}
            </div>
            <div class="form-group">
                <label for="category"><strong>{{ form.category.label_tag }}</strong></label>
                {{ form.category }}
            </div>
            <br>
            <button type="submit" value="Save"><h4>Save</h4></button>
        </form>
        <hr>
    </div>
</div>
{% endblock %}

homepage/templates/schedule_form.html
{% extends 'base.html' %}

{% block title %} {{title}}{% endblock %}

{% load staticfiles %}

{% block content %}
    <div id="sched">
        <div class="container">
            <h1>Schedule</h1>
			<hr>
            <form class="left" style="width: 50%; margin: 0 auto" method="POST" action="{% url 'homepage:schedule_add' %}" novalidate>
                {% csrf_token %}
                <div class="form-group">
                    <label for="activity"><strong>{{ form.activity.label_tag }}</strong></label>
                    {{ form.activity }}
                </div>
                <div class="form-group">
                    <label for="dates"><strong>{{ form.dates.label_tag }}</strong></label>
                    {{ form.dates }}
                </div>
                <div class="form-group">
                    <label for="time"><strong>{{ form.time.label_tag }}</strong></label>
                    {{ form.time }}
                </div>
                <div class="form-group">
                    <label for="location"><strong>{{ form.location.label_tag }}</strong></label>
                    {{ form.location }}
                </div>
                <div class="form-group">
                    <label for="category"><strong>{{ form.category.label_tag }}</strong></label>
                    {{ form.category }}
                </div>
                <br>
                <button type="submit" value="Save"><h4>Add</h4></button>
            </form>
            <hr>
        </div>
    </div>
{% endblock %}

homepage/templates/skill.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %} Skill {% endblock %}

{% block content %}
	<section id="skill">
		<h1>Skill</h1>
		<hr>
		<div class="container">
			<div class="row" id="hardskil">
				<div class="col-md-6">
					<h4>HTML</h4>
					<div class="progress">
					  <div class="progress-bar" role="progressbar" style="width: 85%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">85%</div>
					</div>
					<h4>CSS</h4>
					<div class="progress">
					  <div class="progress-bar" role="progressbar" style="width: 80%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">80%</div>
					</div>
					<h4>Python</h4>
					<div class="progress">
					  <div class="progress-bar" role="progressbar" style="width: 70%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">70%</div>
					</div>
					<h4>Java</h4>
					<div class="progress">
					  <div class="progress-bar" role="progressbar" style="width: 70%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">70%</div>
					</div>
					<h4>Video Editing</h4>
					<div class="progress">
					  <div class="progress-bar" role="progressbar" style="width: 80%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">80%</div>
					</div>
				</div>
				<div class="col-md-6">
					<h4>Creative</h4>
					<div class="progress">
					  <div class="progress-bar" role="progressbar" style="width: 85%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">85%</div>
					</div>
					<h4>Leadership</h4>
					<div class="progress">
					  <div class="progress-bar" role="progressbar" style="width: 75%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">75%</div>
					</div>
					<h4>Time Management</h4>
					<div class="progress">
					  <div class="progress-bar" role="progressbar" style="width: 72%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">72%</div>
					</div>
					<h4>Public Speaking</h4>
					<div class="progress">
					  <div class="progress-bar" role="progressbar" style="width: 70%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">70%</div>
					</div>
					<h4>Adaptive</h4>
					<div class="progress">
					  <div class="progress-bar" role="progressbar" style="width: 70%;" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100">70%</div>
					</div>
				</div>
			</div>
		</div>	
	</section>
{% endblock %}